#!/usr/bin/env python3
"""Generate references/api_catalog.md from abqlib docstrings (plain Python 3.9+).

    python3 tools/gen_catalog.py          # write the catalog
    python3 tools/gen_catalog.py --check  # exit 1 if the catalog is stale

The catalog is what the AI reads to pick functions, so it is generated from
the code and must never be edited by hand.
"""

import ast
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, 'scripts', 'abqlib')
OUT = os.path.join(ROOT, 'references', 'api_catalog.md')

# Display order = typical build order of a script.
ORDER = ['session', 'sets', 'rp', 'constraints', 'bcs', 'loads', 'mass',
         'steps', 'job', 'odb', 'cleanup', 'util']

HEADER = """# abqlib API Catalog

<!-- GENERATED by tools/gen_catalog.py from scripts/abqlib docstrings. Do not edit by hand. -->

Pick functions from this catalog and compose them into a noGUI script
(start from `scripts/skill_template.py`). Every `ensure_*` is idempotent
(delete-if-exists, then create), so re-running the script is safe.

```python
import sys
sys.path.insert(0, SKILL_SCRIPTS_DIR)      # from the User inputs block
from abqlib import session, sets, rp, constraints, bcs, loads, mass, steps, job, odb, cleanup
from abqlib.util import Report, get_last_step
```

Units: mm, N, tonne, s, MPa, N*mm, mm/s^2 (1 g = 9806.65).
If no function fits, write the API call directly using
`references/abaqus_api.md`, and consider adding it to abqlib afterwards.

"""


def _sig(fn):
    src = ast.unparse(fn.args)
    return '%s(%s)' % (fn.name, src)


def _first_para(doc):
    if not doc:
        return '(undocumented)'
    return ' '.join(doc.strip().split('\n\n')[0].split())


def build():
    names = sorted([f[:-3] for f in os.listdir(PKG)
                    if f.endswith('.py') and f != '__init__.py'],
                   key=lambda n: (ORDER.index(n) if n in ORDER else 99, n))
    parts = [HEADER, '## Categories\n\n| Module | What it covers |\n|---|---|\n']
    bodies = []
    for name in names:
        with open(os.path.join(PKG, name + '.py'), encoding='utf-8') as f:
            tree = ast.parse(f.read())
        mod_doc = _first_para(ast.get_docstring(tree))
        parts.append('| `%s` | %s |\n' % (name, mod_doc))
        body = ['\n## `abqlib.%s`\n\n%s\n\n| Function | Does |\n|---|---|\n' % (name, mod_doc)]
        for node in tree.body:
            if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
                body.append('| `%s` | %s |\n' % (_sig(node).replace('|', '\\|'),
                                                  _first_para(ast.get_docstring(node)).replace('|', '\\|')))
            elif isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
                body.append('| `%s` (class) | %s |\n' % (node.name,
                                                          _first_para(ast.get_docstring(node)).replace('|', '\\|')))
        bodies.append(''.join(body))
    return ''.join(parts) + ''.join(bodies)


def main():
    text = build()
    if '--check' in sys.argv:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != text:
            print('api_catalog.md is stale: run python3 tools/gen_catalog.py')
            sys.exit(1)
        print('api_catalog.md up to date')
        return
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    print('wrote %s' % OUT)


if __name__ == '__main__':
    main()
